const $=s=>document.querySelector(s);let timer;
async function json(path,options){const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(data.error||r.statusText);return data}
function cell(value,cls=''){return `<td class="${cls}">${value}</td>`}
function renderServices(data){const root=$('#services');root.innerHTML='';let online=0,offline=0;const services=data.services||{};Object.entries(services).forEach(([name,items])=>(items||[]).forEach(item=>{item.healthy?online++:offline++;root.insertAdjacentHTML('beforeend',`<tr>${cell(name)}${cell(item.addr)}${cell(item.weight)}${cell(item.healthy?'在线':'失活',item.healthy?'healthy':'unhealthy')}</tr>`)}));if(!root.children.length)root.innerHTML='<tr><td colspan="4">暂无实例</td></tr>';$('#serviceSummary').textContent=`在线 ${online} · 失活 ${offline}`}
function renderPools(data){const root=$('#pools');root.innerHTML='';(data.pools||[]).forEach(p=>root.insertAdjacentHTML('beforeend',`<tr>${cell(p.addr)}${cell(p.active)}${cell(p.idle)}${cell(p.capacity)}${cell(p.waiting)}</tr>`));if(!root.children.length)root.innerHTML='<tr><td colspan="5">尚未创建连接池</td></tr>'}
function renderMetrics(m){const values=[['QPS',m.qps.toFixed(2)],['成功率',m.success_rate.toFixed(1)+'%'],['平均延迟',m.average_latency_ms.toFixed(2)+' ms'],['P99',m.p99_latency_ms.toFixed(2)+' ms'],['请求',m.requests],['成功',m.successes],['失败',m.failures],['重试/超时',`${m.retries} / ${m.timeouts}`]];$('#metrics').innerHTML=values.map(([k,v])=>`<div class="card"><small>${k}</small><b>${v}</b></div>`).join('');draw(m.series||[])}
function draw(points){const c=$('#chart'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=26;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#27324b';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p+(h-p*2)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}const max=Math.max(1,...points.map(x=>x.qps));plot(points.map(x=>x.qps/max),'#5eead4');plot(points.map(x=>x.success_rate/100),'#4ade80');function plot(values,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=p+(w-p*2)*i/Math.max(1,values.length-1),y=h-p-v*(h-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
async function refresh(){try{const [services,metrics,pools,config]=await Promise.all([json('/api/services'),json('/api/metrics'),json('/api/pools'),json('/api/config')]);renderServices(services);renderMetrics(metrics);renderPools(pools);$('#config').textContent=JSON.stringify(config,null,2);if(config.selector)$('#selector').value=config.selector;$('#updated').textContent='最后刷新 '+new Date().toLocaleTimeString()}catch(e){$('#updated').textContent='刷新失败: '+e.message}}
function schedule(){clearInterval(timer);timer=setInterval(refresh,Number($('#interval').value))}
$('#refresh').onclick=refresh;$('#interval').onchange=schedule;$('#selector').onchange=async e=>{await json('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selector:e.target.value})});refresh()};schedule();refresh();
